# HyperFleet E2E - golangci-lint configuration
# Follows HyperFleet architecture testing standards

# This file contains only configs which differ from defaults.
# All possible options can be found at https://golangci-lint.run/usage/configuration

version: 2

run:
  timeout: 5m
  tests: true
  go: '1.25'

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 120

  unused:
    check-exported: false

  unparam:
    check-exported: false


linters:
  enable:
    - errcheck       # Check for unchecked errors
    - govet          # Vet examines Go source code
    - ineffassign    # Detect ineffectual assignments
    - staticcheck    # Go static analysis
    - unused         # Check for unused code
    - misspell       # Check for misspelled words
    - unconvert      # Remove unnecessary type conversions
    - unparam        # Find unused function parameters
    - gosec          # Security issues

issues:
  exclude-dirs:
    - pkg/api  # Generated code directory

  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - gosec       # Security checks less critical in tests
        - errcheck    # Error checking less critical in tests
        - unparam     # Unused params acceptable in test helpers

    # Exclude linters from e2e test files (.go suffix, not _test.go)
    - path: e2e/.*\.go
      linters:
        - errcheck    # E2E tests may skip error checks for readability
        - unparam     # Test helpers may have unused params

    # Exclude generated code
    - path: pkg/api/.*\.gen\.go
      linters:
        - all

  # Maximum issues count per one linter
  max-issues-per-linter: 0

  # Maximum count of issues with the same text
  max-same-issues: 0

  # Show only new issues
  new: false

output:
  formats:
    colored-line-number:
      path: stdout
  print-issued-lines: true
  print-linter-name: true
